name: Build and Push Docker Image to Artifactory

on:
  push:
    branches:
      - feature/ECS-cluster-module  

permissions:
  id-token: write

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug - Check Dockerfile Location
        run: ls -l ./app/cat-gifs

      - name: Push Docker Image to Artifactory
        run: |
          docker build -t cat-gif:latest ./app/cat-gifs
          docker images
          echo "${{ secrets.ARTIFACTORY_PASSWORD }}" | docker login ${{ secrets.ARTIFACTORY_URL }} -u ${{ secrets.ARTIFACTORY_USERNAME }} --password-stdin
          docker tag cat-gif:latest ${{ secrets.ARTIFACTORY_URL }}/docker-images/cat-gif:latest
          docker push ${{ secrets.ARTIFACTORY_URL }}/docker-images/cat-gif:latest

  terraform-deploy:
    name: Terraform Init, Plan, Apply
    runs-on: ubuntu-latest
    needs: build-and-push 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::156041426734:role/ActionRole
          aws-region: us-east-2

      - name: Initialize Terraform
        run: terraform init
        working-directory: app/iac

      - name: Run Terraform Plan
        run: terraform plan
        working-directory: app/iac

      - name: Apply Terraform Changes
        run: terraform destroy -auto-approve
        working-directory: app/iac

